#!/bin/sh

cd ~

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unsef f
fi

export PATH=$PATH:/usr/local/google/home/hmclauchlan/bin
eval $(ssh-agent)
while true; do
	i3
	if [ $? -ne 129 ]; then
		break
	fi
done
# kill
kill $(jobs -p)
